name: recipes_app
description: "A recipes app demo"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  go_router: ^14.0.2
  dartz: ^0.10.1
  get_it: ^7.7.0
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  injectable: ^2.4.1
  cached_network_image: ^3.3.1
  event_bus: ^2.0.0
  easy_debounce: ^2.0.3
  logger: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.3
  animate_do: ^3.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  flutter_gen_runner: ^5.4.0



flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
